Refactoring done (SignIn, SignUp)
joshkhdev/psy-assist-platform-ui pull request #19
Opened 2024-07-04 08:02 UTC by A1exShap

2024-07-05 09:05 UTC, miitrei approved these changes

2024-07-08 17:39 UTC, joshkhdev requested changes

2024-07-08 17:39 UTC, joshkhdev commented on src/components/common/Validation.tsx
> +    try {
Не стоит использовать try/catch для простой валидации, воспользуйся пожалуйста safeParse
https://zod.dev/?id=safeparse

2024-07-09 09:00 UTC, joshkhdev approved these changes

2024-07-09 09:00 UTC, merged