Страница отзывов
joshkhdev/psy-assist-platform-ui pull request #25
Opened 2024-08-16 22:22 UTC by miitrei

2024-08-18 16:43 UTC, joshkhdev requested changes
Убери пожалуйста moment.js, этот пакет очень громоздкий
https://bundlephobia.com/package/moment@2.30.1

2024-08-18 16:43 UTC, joshkhdev commented on src/components/pages/FeedbackList.tsx
> +                        <td>{moment(elem.feedbackDate).format('lll')}</td>
format('lll') Это какой формат?
Еще я бы хотел избежать использования библиотек со временем для решения задач вывода
Написать специальную функцию пусть будет более громоздко, зато надежнее и понятнее

2024-08-22 14:57 UTC, A1exShap approved these changes

2024-08-26 21:16 UTC, miitrei commented on src/components/pages/FeedbackList.tsx
> +                        <td>{moment(elem.feedbackDate).format('lll')}</td>
done

2024-08-27 14:53 UTC, joshkhdev approved these changes

2024-09-02 16:14 UTC, merged